# Configuration file for `shelly` static Powershell analyzer:
# https://github.com/krdln/shelly

[levels]
# Insert custom lint levels here

[extras]
cmdlets = [
    "Connect-VBRServer",
    "Disconnect-VBRServer",
    "Start-VBRZip",
    "Find-VBRViEntity",
    "Test-NetConnection",
    "Get-NetFirewallProfile",
    "vrfstats",
    "contrail-nodemgr"
]
