---

- name: Create inventory with deployer
  when: deployer_inventory_file is defined
  template:
    src: deployers.inventory.j2
    dest: "{{ deployer_inventory_file }}"

- name: Fetch inventory with deployer
  when: deployer_inventory_file is defined
  command: "cat {{ deployer_inventory_file }}"
  register: cat_deployer_inventory

- name: Print inventory with deployer
  when: (cat_deployer_inventory is defined) and (cat_deployer_inventory|succeeded)
  debug:
    var: cat_deployer_inventory.stdout_lines
