---

- name: Get highest VM number
  delegate_to: localhost
  register: get_vm_id
  script: >
    get_vm_id.py
    --host '{{ vcenter_hostname }}'
    --user '{{ vcenter_username }}'
    --password '{{ vcenter_password }}'
    --vm-name "winci-{{ vm_role }}-"

- name: "Deploy VM from Template: winci-{{ vm_role}}-{{ get_vm_id.stdout.strip() }}"
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"

    datacenter: "{{ vcenter_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    folder: "{{ vmware_folder }}"

    name: "winci-{{ vm_role}}-{{ get_vm_id.stdout.strip() }}"
    annotation: "Template for {{ vm_role }} created on {{ '%Y-%m-%d %H:%M:%S' | strftime(ansible_date_time.epoch) }}"
    template: "{{ vm_template }}"
    hardware: "{{ vm_hardware }}"
    state: poweredon
    customization:
      hostname: "winci-{{ vm_role }}-{{ get_vm_id.stdout.strip() }}"
      password: "Contrail123!"

    networks: "{{ vm_networks }}"

- name: Wait for VMware tools to come up after cloning base template
  vmware_guest_tools_wait:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    folder: "{{ template_folder }}"
    name: "{{ template_name }}"

# NOTE: "Workaround". One way to check if customization has finished is to check hostname through
#       VMware Tools, but vmware_guest_facts does not support this.
#       Need to research it.
- name: Wait for customization to finish (workaround by sleeping)
  wait_for:
    timeout: 900

- name: Wait for correct IP address
  vmware_guest_facts:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    folder: "{{ template_folder }}"
    name: "{{ template_name }}"
  register: vm
  retries: 60
  delay: 15
  until: >
      vm.instance.hw_eth0.ipaddresses | ipv4 | reject("match", "169.254.*") | list

- debug:
    var: vm

- name: Add host to inventory
  add_host:
    name: "winci-{{ vm_role }}-{{ get_vm_id.stdout.strip() }}"
    ansible_host: "{{ vm.instance.hw_eth0.ipaddresses | ipv4 | first }}"
    groups: "{{ vm_role }}"
