---

- name: Power Off Template-{{ vm_role }}
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    name: "{{ new_vm.instance.hw_name }}"
    uuid: "{{ new_vm.instance.hw_product_uuid }}"
    state: shutdownguest

- name: Wait for Template-{{ vm_role }} to shutdown
  register: shutdownvm
  vmware_guest_facts:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"

    datacenter: "{{ vcenter_datacenter }}"

    uuid: "{{ new_vm.instance.hw_product_uuid }}"
  retries: 60
  delay: 5
  until: >
      shutdownvm.instance.hw_power_status == "poweredOff"
