---

- name: Power Off Template-{{ vm_role }}
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    folder: "{{ template_folder }}"
    name: "{{ template_name }}"
    state: shutdownguest

- name: Wait for Template-{{ vm_role }} to shutdown
  register: shutdownvm
  vmware_guest_facts:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    folder: "{{ template_folder }}"
    name: "{{ template_name }}"
  retries: 60
  delay: 5
  until: >
      shutdownvm.instance.hw_power_status == "poweredOff"
