---

- name: Shutdown VM
  include_tasks: "shutdown.yml"

- name: Turn VM into a template
  delegate_to: localhost
  script: >
    mark_vm_as_template.py
    --host '{{ vcenter_hostname }}'
    --user '{{ vcenter_username }}'
    --password '{{ vcenter_password }}'
    --uuid "{{ template_vm_uuid }}"
