---

# Need to install first, to set feature before downloading any package
- name: ensure Chocolatey itself is installed
  win_chocolatey:
    name: chocolatey
    state: present

# Fix for incompability of Ansible and choco
# https://github.com/chocolatey/choco/wiki/ReleaseNotes#01012---march-14-2019
- name: disable choco enhanced exit codes
  win_shell: |
    choco feature disable --name="'useEnhancedExitCodes'"

- name: Install Telegraf
  win_chocolatey:
    name: telegraf
    state: present

- name: Copy Telegraf config file
  win_template:
    src: telegraf.conf.j2
    dest: '{{ telegraf_path }}\telegraf.conf'
    force: yes

- name: Add telegraf to PATH
  win_path:
    elements:
    - '{{ telegraf_path }}'
    state: present

- name: Start telegraf service
  win_service:
    name: telegraf
    state: started
