---

- name: Include windows-common role
  include_role:
    name: windows-common

- name: Install python 2.7.13
  win_chocolatey:
    name: python2
    version: 2.7.13
    state: present

- name: Install feature Windows-Containers
  win_feature:
    name: 'Containers'
    state: present

- name: Install feature NET-Framework-Features
  win_feature:
    name: 'NET-Framework-Features'
    state: present

- name: Install feature Hyper-V
  win_feature:
    name: 'Hyper-V'
    include_management_tools: True
    state: present

- name: Install DockerMsftProvider
  win_psmodule:
    name: DockerMsftProvider

- name: Reboot the system
  win_reboot:
    test_command: powershell.exe 'Get-WindowsFeature'
    pre_reboot_delay: 15
    post_reboot_delay: 15

- name: Wait for reconnection
  wait_for_connection:

- name: Install Docker-EE
  win_shell: "Install-Package Docker -ProviderName DockerMsftProvider -RequiredVersion 18.03 -Force"

- name: Make sure docker is started
  win_service:
    name: Docker
    state: started
    start_mode: auto

- name: Set Windows Server version var
  set_fact:
    windows_server_version: "{{ ansible_distribution | regex_findall('Windows Server (\\d{4})') | first }}"

- name: Pull Microsoft docker images (Windows Server 2016)
  win_shell: "docker pull {{ item }}"
  with_items:
    - microsoft/nanoserver
    - microsoft/windowsservercore
  when: windows_server_version == '2016'

- name: Pull Microsoft docker images (Windows Server 2019)
  win_shell: "docker pull {{ item }}"
  with_items:
    - mcr.microsoft.com/windows/servercore:1809
    - mcr.microsoft.com/windows/nanoserver:1809
  when: windows_server_version == '2019'

- name: Pull docker python image
  win_shell: "docker pull python:3.7"

- name: Install VC for Python 2.7
  win_chocolatey:
    name: vcpython27
    version: 9.0.0.30729
    state: present

- name: Install MS Visual C++ Redists
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
  - vcredist2013
  - vcredist2015

- name: Disable Windows Firewall
  win_firewall:
    profiles:
      - Domain
      - Private
    state: disabled

- name: Stop Docker
  win_service:
    name: docker
    state: stopped

- name: Remove NetNat objects
  win_shell: |
    Get-NetNat | Remove-NetNat -Confirm:$false

# Workaround for flaky HNS behavior.
# Removing container networks sometimes ends with "Unspecified error".
# For environment cleanup in tests it is acceptable to just ignore this error
# (-ErrorAction SilentlyContinue). However, this is not acceptable for
# template creation (we don't want to have unreliable template).
- name: Remove container networks on Windows Server 2016
  win_shell: |
    Get-ContainerNetwork | Remove-ContainerNetwork -ErrorAction SilentlyContinue -Force
    Get-ContainerNetwork | Remove-ContainerNetwork -Force
  when: windows_server_version == '2016'

- name: Remove container networks on Windows Server 2019
  win_shell: |
    Get-HnsNetwork | Remove-HnsNetwork
  when: windows_server_version == '2019'

- name: Create docker config directory
  win_file:
    path: 'C:\ProgramData\Docker\config'
    state: directory

- name: Disable docker's nat network
  win_copy:
    dest: 'C:\ProgramData\Docker\config\daemon.json'
    content: |
      {
        "bridge" : "none"
      }

# Workaround (#1) for Docker/Windows behavior.
# When WinNAT is enabled and NetNat object associated with default bridge
# network created by Docker exists, ICMP/UDP packets bigger than MTU do
# not reach containers and the host itself.
# Workaround (#2) for win_service behavior.
# We use win_shell instead of win_service because for this particular service
# win_service seems to fail ("An error occurred while creating the pipeline")
# while it works fine for other services like Docker.
- name: Stop  WinNAT
  win_shell: Stop-Service winnat

- name: Disable WinNAT
  win_shell: Set-Service -StartupType Disabled -Name winnat

- name: Enable testsigning
  win_shell: |
    Bcdedit.exe -set TESTSIGNING ON

- name: Install NSSM
  win_chocolatey:
    name: nssm
    state: present

- name: Downloading python libs for DNS server
  win_shell: |
    New-Item -ItemType directory -Path C:\DockerFiles\python-dns -Force
    pip download dnslib==0.9.7 --dest C:\DockerFiles\python-dns
    pip install C:\DockerFiles\python-dns\dnslib-0.9.7.tar.gz
    pip install pathlib==1.0.1
