- name: 'apt update && upgrade'
  apt:
      update_cache: yes
      upgrade: safe


- name: 'install apache'
  apt:
      name: apache2
      state: present

- name: 'copy apache config'
  register: new_apache_config
  copy:
      src: '{{ config_dir }}/apache2/conf-available/'
      dest: /etc/apache2/conf-available/

- name: 'enable apache config'
  file:
      src: ../conf-available/zuul.conf
      dest: /etc/apache2/conf-enabled/zuul.conf
      state: link

- name: 'reload apache'
  service:
      name: apache2
      state: restarted
  when: new_apache_config.changed


- name: 'install pip'
  apt:
      name: python-pip
      state: present

- name: 'install zuul using pip'
  pip:
      name: zuul
      version: 2.6.0

- name: 'install gearman using pip'
  pip:
      name: gearman
      version: 2.0.2


- name: 'copy zuul config files'
  copy:
      src: '{{ config_dir }}/zuul/'
      dest: /etc/zuul/

- name: 'copy zuul .service files'
  copy:
      src: '{{ config_dir }}/services/'
      dest: /lib/systemd/system/

- name: 'add zuul group'
  group:
      name: zuul
      state: present

- name: 'add zuul user'
  user:
      name: zuul
      group: zuul

- name: 'create zuul directories in /var'
  file:
      path: '{{ item }}'
      state: directory
      owner: zuul
      group: zuul
  with_items:
      - /var/lib/zuul
      - /var/lib/zuul/ssh
      - /var/log/zuul

- name: 'copy id_rsa'
  copy:
      src: '{{ id_rsa_path }}'
      dest: /var/lib/zuul/ssh

- name: 'enable zuul server service'
  service:
      name: zuul-server
      enabled: yes

- name: 'enable zuul merger service'
  service:
      name: zuul-merger
      enabled: yes
