---
- name: Set PowerShell as a default shell
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: Shell
    data: powershell.exe

- name: Enable Remote Desktop
  win_shell: cscript C:\Windows\System32\Scregedit.wsf /ar 0

# Need to install first, to set feature before downloading any package
- name: install choco
  win_chocolatey:
    name: chocolatey
    state: latest

# Fix for incompability of Ansible and choco
# https://github.com/chocolatey/choco/wiki/ReleaseNotes#01012---march-14-2019
- name: disable choco enhanced exit codes
  win_shell: |
    choco feature disable --name="'useEnhancedExitCodes'"
