pipelines:
  - name: production
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Windows CI.
    failure-message: Build failed.
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
          branch: ^master$
        - event: change-restored
          branch: ^master$
        - event: comment-added
          branch: ^master$
          comment: (?i)recheck(( (?:bug|lp)[\s#:]*(\d+))|( no bug))(\s+clean)?\s*$
        - event: comment-added
          comment: (?i)recheck windows$

  - name: production-windows
    description: Newly uploaded patchsets only from Wincontrail enter this pipeline.
    failure-message: Build failed.
    footer-message: > 
                      This is a pipeline from Windows CI. For more information, see:
                      https://github.com/codilime/contrail-windows-ci/wiki/OpenContrail-Windows-CI-FAQ
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
          branch: ^master$
          email: &win_email_whitelist
            - ^.*?@codilime\.com$
            - ^sagarc@juniper\.net$
        - event: change-restored
          branch: ^master$
          email: *win_email_whitelist
        - event: comment-added
          branch: ^master$
          comment: (?i)recheck(( (?:bug|lp)[\s#:]*(\d+))|( no bug))(\s+clean)?\s*$
          email: *win_email_whitelist
        - event: comment-added
          comment: (?i)recheck windows$
          email: *win_email_whitelist
    start:
      gerrit: {}
    success:
      gerrit: {}
    failure:
      gerrit: {}

  - name: development
    description: Pipeline used for Windows CI development. It should always work in silent mode.
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      gerrit:
        - event: comment-added
          comment: (?i)recheck windows(?:-| )(dev|devel|development)\s*$

project-templates:
  - name: ci-contrail-windows-template
    production:
      - ci-contrail-windows-production
    production-windows:
      - ci-contrail-windows-production
    development:
      - ci-contrail-windows-development

projects:
  - name: Juniper/contrail-controller
    template:
      - name: ci-contrail-windows-template

  - name: Juniper/contrail-vrouter
    template:
      - name: ci-contrail-windows-template

  - name: Juniper/contrail-build
    template:
      - name: ci-contrail-windows-template

  - name: Juniper/contrail-third-party
    template:
      - name: ci-contrail-windows-template

  - name: Juniper/contrail-generateDS
    template:
      - name: ci-contrail-windows-template

  - name: Juniper/contrail-sandesh
    template:
      - name: ci-contrail-windows-template

  - name: Juniper/contrail-common
    template:
      - name: ci-contrail-windows-template
