---

- name: Install dependencies on deployer machine
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - sshpass
    - python-pip

- name: Install dependencies on deployer machine through PIP
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
  with_items:
    - name: ansible
      version: 2.4.2
    - name: requests

- name: Upload contrail-ansible-deployer do deployer machine
  copy:
    src: "../contrail-ansible-deployer"
    dest: "./contrail-ansible-deployer"

- name: Upload debug dlls do deployer machine
  copy:
    src: "../dlls"
    dest: "./dlls"

- name: Run deployer playbooks
  include_tasks: ../contrail-ansible-deployer/tasks/run_deployer_playbook.yml
  vars:
    playbook: '{{ item.playbook }}'
    extra_options: '{{ item.extra_options | default("") }}'
    docker_provision_dir: "contrail-ansible-deployer"
  with_items:
    - { playbook: 'playbooks/configure_instances.yml', extra_options: '-v' }
    - { playbook: 'playbooks/install_contrail.yml'}
