---
- name: Deploy testenv VMs
  delegate_to: localhost
  shell: >
    '{{ script_path.path }}/provision_vm.py'
    --host '{{ vcenter_hostname }}'
    --user '{{ vcenter_user }}'
    --password '{{ vcenter_password }}'
    --datacenter '{{ datacenter_name }}'
    --datastore-cluster '{{ datastore_cluster_name }}'
    --template '{{ hostvars[inventory_hostname].template }}'
    --folder '{{ testenv_folder }}'
    --name '{{ inventory_hostname_short }}'
    --mgmt-network '{{ portgroup_mgmt }}'
    --data-network '{{ portgroup_contrail }}'
    --data-ip-address '{{ hostvars[inventory_hostname].ip }}'
    --data-netmask '{{ hostvars[inventory_hostname].netmask }}'
    {{ hostvars[inventory_hostname].provision_options }}

- name: Include common post-deploy tasks
  include_tasks: "post_deploy.yml"
