---

- name: Destroy VM '{{ inventory_hostname }}'
  delegate_to: localhost
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ validate_certs }}"

    folder: "{{ datacenter_name }}/vm/{{ testenv_folder }}"

    name: "{{ inventory_hostname_short }}"
    state: absent
    force: yes
