---

- name: "Add Contrail controller VMs to ad-hoc inventory for testenv '{{ testenv_name }}'"
  add_host:
    name: "{{ item.name }}"
    groups: testenv,controller
    type: controller
    template: "{{ provisioning.vms.controller.template }}"
    testenv_name: "{{ provisioning.name }}"
    testenv_folder: "{{ provisioning.folder }}"
    portgroup_mgmt: "{{ provisioning.portgroup_mgmt }}"
    portgroup_contrail: "{{ provisioning.portgroup_contrail }}"
  with_items:
    "{{ provisioning.vms.controller.nodes }}"

- name: "Add Windows testbed VMs to ad-hoc inventory for testenv '{{ testenv_name }}'"
  add_host:
    name: "{{ item.name }}"
    groups: testenv,testbed,windows
    type: wintb
    ip: "{{ item.ip }}"
    netmask: "{{ provisioning.vms.wintb.netmask }}"
    template: "{{ provisioning.vms.wintb.template }}"
    testenv_name: "{{ provisioning.name }}"
    testenv_folder: "{{ provisioning.folder }}"
    portgroup_mgmt: "{{ provisioning.portgroup_mgmt }}"
    portgroup_contrail: "{{ provisioning.portgroup_contrail }}"
  with_items:
    "{{ provisioning.vms.wintb.nodes }}"

- name: Display inventory for 'testenv' group
  debug:
    verbosity: 1
    msg: "{{ item }}, groups: {{ hostvars[item].group_names }}"
  with_inventory_hostnames: testenv
