- name: Upgrade system
  apt:
    update_cache: yes
    upgrade: full
  become: true

- name: Reboot system
  shell: sleep 2 && /sbin/shutdown -r now
  become: true
  async: 5
  poll: 0
  ignore_errors: true

- name: Wait for the server to boot up
  wait_for_connection:
    sleep: 5
    timeout: 60
