---

- hosts: jenkins-server
  roles:
  - jenkins.system-setup
  - geerlingguy.jenkins
  - { role: ssh-key, username: jenkins }
  - jenkins.keys

#- hosts: ansible-worker
#  roles:
#  - wurbanski.jenkins-swarm-agent

# Run this before other Windows roles, since they may need the shared drive to be up
- hosts: drive
  roles:
  - shared-drive

#- hosts: builder
#  roles:
#  - builder
#  - wurbanski.jenkins-swarm-agent

#- hosts: tester
#  roles:
#  - tester
#  - wurbanski.jenkins-swarm-agent

#- hosts: testbed
#  roles:
#  - testbed
#  - wurbanski.jenkins-swarm-agent
