---
- hosts: localhost
  gather_facts: no
  connection: local
  roles:
  - testenv-inventory-build

- hosts: testenv
  gather_facts: no
  strategy: free
  roles:
  - role: vmware-vm
    action: destroy
