---

- hosts: localhost
  connection: local
  roles:
    - { role: vmware-template, stage: create }

- hosts: "{{ vm_role }}"
  gather_facts: no
  tasks:
    - name: "Wait for new {{ vm_role }} template to become reachable"
      wait_for_connection:
        sleep: 5
        timeout: 900

- hosts: "{{ vm_role }}"
  roles:
    - "{{ vm_role }}"

- hosts: localhost
  connection: local
  tasks:
    - name: Create snapshot
      include_role:
        name: vmware-template
      vars:
        stage: snapshot
      when: vm_role == "testbed"

- hosts: localhost
  connection: local
  roles:
    - { role: vmware-template, stage: template }
