---

- name: Create instances.yaml
  when: instances_file is defined
  template:
    src: testenv-instances.yml.j2
    dest: "{{ instances_file }}"

- name: Fetch instances.yaml
  when: instances_file is defined
  command: "cat {{ instances_file }}"
  register: cat_instances

- name: Print instances.yaml
  when: (instances_file is defined) and (cat_instances|succeeded)
  debug:
    var: cat_instances.stdout_lines
